apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: frontend
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - frontend.hipstershop-staging.demo1.keptn.live.demo.dynatrace.com
  - frontend
  http:
  - route:
    - destination:
        host: frontend.hipstershop-staging.svc.cluster.local
